---
title: "class04"
author: "Kyle Dodson"
date: "2026-09-02"
output: 
  html_document:
    toc: true
    toc_float: true
    numer_section: true
    code_download: true
    code_folding: show
    
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r}
crashes_by_day = c(2020, 2241, 2327, 2285, 2380, 1866, 1664)
names(crashes_by_day) = c("Mon", "Tue", "Wed", "Thu",
                          "Fri", "Sat", "Sun")

crashes_df = tibble::tibble(
  day     = names(crashes_by_day),
  crashes = crashes_by_day,
  busy    = crashes_by_day > 2000)
crashes_df$crashes                     # one column, as a vector
```
```{r}
crashes_by_day = c(2020, 2241, 2327, 2285, 2380, 1866, 1664)
names(crashes_by_day) = c("Mon", "Tue", "Wed", "Thu",
                          "Fri", "Sat", "Sun")
crashes_by_day

dplyr::glimpse(crashes_df)
```
```{r}
job = list(
  title   = "Research Data Scientist, Magic Eye",
  company = "Google",
  salary  = list(min = 147000, max = 210000)
)
str(job)
dplyr::glimpse(job)

company_name = job$company
company_name_as_named_list = job[2]
max_salary = job$salary$max ### or job[[3]][[2]]
min_salary = job$salary$min ### or job[[3]][[1]]
names(job)


# 1. The company name. 
# 2. The maximum salary.
# 3. The maximum salary again, using only [[ ]].
# 4. The names of the elements in job.

```

# Subsetting (a.k.a getting a subset of the object's data for analysis)

## Vectors

- You can subset by position (i.e., a number) or by name if it is a named vector;
- You can also pass a vecctor (e.g., a logical condition 2:4 or c() ) for 
subsetting the vector

```{r}
crashes_by_day = c(2020, 2241, 2327, 2285, 2380, 1866, 1664)
names(crashes_by_day) = c("Mon", "Tue", "Wed", "Thu",
                          "Fri", "Sat", "Sun")
crashes_by_day[2:4] # you can give consecutive numbers
crashes_by_day[c('Mon', 'Fri')] # crashes by day 
```
```{r}
crashes_by_day[c(2, 4)]
crashes_by_day['Sat']
crashes_df$day[crashes_df$crashes < 2000]
crashes_df[["busy"]][3]
job["salary"]$max
```

```{r jobs}
oh_jobs = readr::read_csv(
  file = "https://fred.stlouisfed.org/graph/fredgraph.csv?bgcolor=%23ebf3fb&chart_type=line&drp=0&fo=open%20sans&graph_bgcolor=%23ffffff&height=450&mode=fred&recession_bars=on&txtcolor=%23444444&ts=12&tts=12&width=1140&nt=0&thu=0&trc=0&show_legend=yes&show_axis_titles=yes&show_tooltip=yes&id=IHLIDXUSOH&scale=left&cosd=2021-08-28&coed=2026-08-28&line_color=%230073e6&link_values=false&line_style=solid&mark_type=none&mw=3&lw=3&ost=-99999&oet=99999&mma=0&fml=a&fq=Daily%2C%207-Day&fam=avg&fgst=lin&fgsnd=2020-02-01&line_index=1&transformation=lin&vintage_date=2026-09-02&revision_date=2026-09-02&nd=2020-02-01", )
```